# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1441, 1024)
        self.Background = QtWidgets.QFrame(Form)
        self.Background.setGeometry(QtCore.QRect(0, 0, 293, 1024))
        self.Background.setStyleSheet("QFrame\n"
"{\n"
"    image: url(:/background/sb.png)\n"
"}\n"
"\n"
"[objectName^=\"b_H\"]::indicator::unchecked\n"
"{\n"
"    image: url(:/buttoninactive/H_0.png)\n"
"}\n"
"\n"
"[objectName^=\"b_H\"]::indicator::unchecked::hover\n"
"{\n"
"    image: url(:/buttonhover/H_1.png)\n"
"}\n"
"\n"
"[objectName^=\"b_H\"]::indicator::checked\n"
"{\n"
"    image: url(:/buttonactive/H_2.png)\n"
"}\n"
"\n"
"[objectName^=\"b_R\"]::indicator::unchecked\n"
"{\n"
"    image:  url(:/buttoninactive/R_0.png)\n"
"}\n"
"\n"
"[objectName^=\"b_R\"]::indicator::unchecked::hover\n"
"{\n"
"    image:  url(:/buttonhover/R_1.png)\n"
"}\n"
"\n"
"[objectName^=\"b_R\"]::indicator::checked\n"
"{\n"
"    image: url(:/buttonactive/R_2.png)\n"
"}\n"
"\n"
"\n"
"[objectName^=\"b_F\"]::indicator::unchecked\n"
"{\n"
"    image:  url(:/buttoninactive/F_0.png)\n"
"}\n"
"\n"
"[objectName^=\"b_F\"]::indicator::unchecked::hover\n"
"{\n"
"    image:  url(:/buttonhover/F_1.png)\n"
"}\n"
"\n"
"[objectName^=\"b_F\"]::indicator::checked\n"
"{\n"
"    image: url(:/buttonactive/F_2.png)\n"
"}\n"
"\n"
"")
        self.Background.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Background.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Background.setObjectName("Background")
        self.b_H = QtWidgets.QRadioButton(self.Background)
        self.b_H.setGeometry(QtCore.QRect(40, 280, 201, 81))
        self.b_H.setText("")
        self.b_H.setChecked(True)
        self.b_H.setObjectName("b_H")
        self.b_R = QtWidgets.QRadioButton(self.Background)
        self.b_R.setGeometry(QtCore.QRect(40, 400, 201, 81))
        self.b_R.setText("")
        self.b_R.setObjectName("b_R")
        self.b_F = QtWidgets.QRadioButton(self.Background)
        self.b_F.setGeometry(QtCore.QRect(40, 520, 201, 81))
        self.b_F.setText("")
        self.b_F.setObjectName("b_F")
        self.sec_frame = QtWidgets.QFrame(Form)
        self.sec_frame.setGeometry(QtCore.QRect(293, 0, 1167, 1044))
        self.sec_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sec_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sec_frame.setObjectName("sec_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sec_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.remv

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
